name: deploy-book

on:
  push:
    branches:
    - main
    # paths:
    # - publish/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install notebook

    - name: Get dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - run: dotnet tool install -g Microsoft.dotnet-interactive
    - run: dotnet interactive jupyter install
    - run: dotnet restore
    - run: dotnet build --no-restore

    - name: Build the book
      run: jupyter-book build ./publish/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_build/html"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
